apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: /metrics
    spec:
      serviceAccountName: {{ .Release.Name }}
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: pulsemesh
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: HTTP_ADDR
              value: ":8080"
            - name: TCP_ADDR
              value: ":9090"
            - name: UDP_ADDR
              value: ":9091"
            - name: LOG_LEVEL
              value: {{ .Values.config.logLevel | quote }}
            - name: QUEUE_CAPACITY
              value: {{ .Values.config.queueCapacity | quote }}
            - name: DLQ_CAPACITY
              value: {{ .Values.config.deadLetterCapacity | quote }}
            - name: WORKERS
              value: {{ .Values.config.workers | quote }}
          ports:
            - name: http
              containerPort: 8080
            - name: tcp
              containerPort: 9090
            - name: udp
              containerPort: 9091
              protocol: UDP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            readOnlyRootFilesystem: true

