apiVersion: v1
kind: Service
metadata:
  name: pulsemesh
  namespace: pulsemesh
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: pulsemesh
  ports:
    - name: http
      port: 8080
      targetPort: http
    - name: tcp
      port: 9090
      targetPort: tcp
    - name: udp
      port: 9091
      targetPort: udp
      protocol: UDP

